version: 0.2
phases:
  pre_build:
    commands:
      - echo "Enter pre-build"
    build:
      commands:
        - echo "Enter build package"
        - mvn clean prepare-package war:explode
      post_build:
        commands:
          - echo "Enter build post -build phase"
          - mv target/deploy ./
        artifacts:
          files:
            -deploy/**/*
